eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: general-server 