spring:
  application:
    name: product-service

server:
  port: 8702


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
  instance:
    hostname: localhost